[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 61.0"]

[project]
authors = [
  {name = "Pawel Plesniak", email = "pawel.plesniak15@imperial.ac.uk"},
  {name = "James Turner", email = "james.turner@imperial.ac.uk"},
   {name = "Marco Roda", email = "marco.roda@liverpool.ac.uk"},
]
dependencies = [
  "click",
  "grpcio",
  "grpcio-status",
  "grpcio-tools",
  "googleapis-common-protos",
  "rich",
]
description = "Schema definitions and compilation script for runconfschema"
name = "runconfschema"
readme = "docs/README.md"
requires-python = ">=3.10"
version = "1.2.1"

[project.optional-dependencies]
dev = ["ruff", "pre-commit", "pytest", "pytest-cov", "mypy-protobuf", "types-protobuf"]

[project.urls]
Documentation = "https://dune-daq-sw.readthedocs.io/en/latest/packages/daq-release/team_repos/?h=runconfschema"
Repository = "https://github.com/DUNE-DAQ/runconfschema"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = "-v --tb=short --cov=runconfschema --cov=src/runconfschema tests/"

[tool.coverage.run]
omit = ["tests/*", "scripts/*"]
source = ["runconfschema"]

[tool.ruff]
exclude = [
  "src/runconfschema.egg-info",
  "src/runconfschema/*_pb2.py*",
  "src/runconfschema/*_pb2_grpc.py*",
]

[tool.ruff.lint]
pydocstyle.convention = "google"
select = [
  "D", # pydocstyle
  "E", # pycodestyle
  "F", # Pyflakes
  "I", # isort
  "UP", # pyupgrade
  "RUF", # ruff-specific rules
  "R", # refactoring suggestions
]
