syntax = "proto3";

package dunedaq.runconfschema;

import "runconfschema/common.proto";

message BootRequest {
  string apparatus = 1;
  string manager_type = 2;   // check with James if this should be an enum;
  string config_file_name = 3;
  string session_id = 4;
  string output_directory = 5;
  optional string base_url = 6;   // how can we generalise the URLs? 
  optional string ops_url = 7;
  // do we need a log level?  

  Endpoint frontend_endpoint = 8;   // the endpoint of the frontend, so that the backend can send messages to it;
}

