syntax = "proto3";

package dunedaq.runconfschema;

import "runconfschema/common.proto";

message DropDownContent {
  repeated string values = 1;   // the list of values to be put in the dropdown menu;
}

// Do we need an initial initialisation request?
message Initialisation {
    string runconf_version = 1;   // the version of the backend;
    string daq_version = 2;   // the version of the DAQ software;
    string apparatus = 3;   // the name of the apparatus;
    map<string,string> structure = 4; // the key the identifier of the dropdown menu, the value is an initial description or string to be put there;
   map<string, DropDownContent> dropdowns = 5;   // the key is the identifier of the dropdown menu,;
   // the size of dropdown menu is not the size of the structue;

   optional string additional_info = 6;   // any additional message to be displayed at the top of the page
   Endpoint backend_endpoint = 7;   // the endpoint of the backend, so that the backend can send messages to it;
}

message DropDownSelection {
  string key = 1;   // the identifier of the dropdown menu;
  string value = 2;  // the selected value from the dropdown menu;
}

message DropDownUpdate {
    Response response = 1;
    map<string, DropDownContent> update = 2;
    repeated string resets = 3;   // list of identifiers of the dropdown menu to be reset to the initial values;  initial values are in the Intialisation message

}

message Open {
    map<string,string> selection =1; // it might be a bit redundant;
}
    
message ConfigurationOutcome {
    Response response = 1;
    string oks_file = 2;   
    string current_file = 3;  
    string session_name = 4;  
}